basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: GopherNet API
  title: GopherNet API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
swagger: "2.0"
